Full NNBD Migration tests included (#24)
* Fixing the way aqueduct TestRequest serializes list query parameters (#4)

* Fixing the way aqueduct TestRequest serializes list query parameters

Up until now list query parameters were serialized in such a way:
`url?query=[1, 2]`. This is not the way aqueduct expects list parameters to
be sent with that pull request the way lists are serialized is:
`url?query=1&query=2`

* Update aqueduct_test/test/request_test.dart

* Nnbd ingegrate deps (#14)

* Fixing problem with deps

* Fixed all Uri errors

* Add back templates

* Change test and main package to version 2.12

* Add workflow back (#15)

* Create dart.yml

* remove macos build

* remove windows test

 Error: Container operations are only supported on Linux runners

* whoops

* remove travis and move appveyor to ci for posterity

* remove badges

* granularize workflows

* Remove caching (#16)

* Create dart.yml

* remove macos build

* remove windows test

 Error: Container operations are only supported on Linux runners

* whoops

* remove travis and move appveyor to ci for posterity

* remove badges

* granularize workflows

* remove cache

* remove cache

* Merge open api and commons (#17)

* Create dart.yml

* remove macos build

* remove windows test

 Error: Container operations are only supported on Linux runners

* whoops

* GitBook: [master] 2 pages and 17 assets modified

* remove travis and move appveyor to ci for posterity

* remove badges

* granularize workflows

* Updated code to use conduit_common and conduit_open_api

* remove cache

* remove cache

Co-authored-by: Brett Sutton <bsutton@noojee.com.au>

* renamed top level directories from aqueduct to conduit.

* change all reference to aqueduct to conduit.

* renamed referencese from Aqueduct to Conduit

* updated packages to a series of renames from aqueduct to conduit.

* Moved templates to their own repo conduit_templates

* Now cleanly compiles with with all of the newly named packags.

* All compiler errors resulting from nnbd migration have now been resolved.

* migrated to nnbd.

* Base map type takes a key? so had to mark as as covarient as tests wouldn't even start.

* databaseType is optional.

* corrected the defaultTo of address to be explicitly 0.0.0.0

* corrected the names of the certs to use conduit rather than aqueduct.

* All serve_test unit tests are passing after sorting out a few nnbd issues.

* Attempts to fixe the can provide a single outage unit test. Still not working correctly.

* updated test directories to be called conduit rather than aqueduct.

* updated references from aqueduct to conduit.

* updated path from github aqueduct to conduit.

* Moved global functions from context_helper to test/db/psotgres/postgres_test_config.dart so that we could change the default port that the unit tests connect to the db on. The test port is now 15432. This was done to avoid conflicting with the users own local postgres install as the unit test now spin up a docker container for postgres.

* Updated unit tests to use alternate psql port 15432 including ci processes.

* Added support for configuring the postgres connection arguments from environment variables.

* Added support for configuring the postgres connection arguments from environment variables.

* initial work on automating setup and running of unit tests.

* Fixed a recursion bug in the factory ctor.

* Now passes in the postgre connection details via environment variables.

* Fixed the migration_test and changed getDatabaseConnection to return an nnbd type as it looks like it will throw if a connection can't be made.

* updated password to match the one created by docker-compose.

* fixed db_validation_test. Looks like all orm fields need to be declared as ? or maybe late given we have a no arg constructor.

* made the httpserver nullable because it is and cleaned up the shutdown logic.

* removed unnecessary cast.

* removed unnecessary cast.

* Fixed migration unit tests by removing unnecessary casts.

* Change String bar to String? bar as it looks like all orm table fields need to be marked as nullable.

* Change maps to require keys are nnbd as it makes no sense to insert a null key into a map. Fixed a number of unit tests with this change.

* Fixed an npe as the intance wrapper can valiidly be null here.

* removed unnecessary cast to fix unit tests update_tests.dart

* Removed a throw when trying for an entity type as the try function should be returning an null. fixes query_test.dart.

* removed invalid type and replaced with var to let dart do its thing. Router for enties by id is now working.

* unit tests for default_resource_controller_test are now passing

* removed extra space.

* tweaked spacing so it matches the unit tests expectations.

* Fixed casting isssues.

* Attempts to get body_decoder_test working. But I think there are some pre-existing problems with futures.

* Added pedantic so we can use unawaited.

* Removed code to changed directories. The intent is that we will move to using aboslute paths for all file system operations. Will fix the issues this change causes as we work through the resulting failed unit test. This change was made to make running unit tests more reliabe as changing directories was causing the unit test framework to fail.

* ignored test generaed files and added vscode launch.json

* change some db tests

* save work

* another chunk of tests done

* http pathing is a bitch

* fix up templates

* haphazardly switching to using port 15432 caused some issues

* update pubspec

Co-authored-by: Reductions <slavi.boyanov@gmail.com>
Co-authored-by: Brett Sutton <bsutton@noojee.com.au>